//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaAutomation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Biletler
    {
        public int ID { get; set; }
        public string BiletNo { get; set; }
        public Nullable<int> MusteriID { get; set; }
        public int FilmID { get; set; }
    
        public virtual Filmler Filmler { get; set; }
        public virtual Musteriler Musteriler { get; set; }
    }
}
