//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaAutomation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filmler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Filmler()
        {
            this.Biletler = new HashSet<Biletler>();
        }
    
        public int ID { get; set; }
        public string FilmAdi { get; set; }
        public string Resim { get; set; }
        public Nullable<int> SalonID { get; set; }
        public Nullable<int> SeansID { get; set; }
        public string Yonetmen { get; set; }
        public string FilmTuru { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Biletler> Biletler { get; set; }
        public virtual Salonlar Salonlar { get; set; }
        public virtual Seanslar Seanslar { get; set; }
    }
}
